### ISSUE TITLE
Can not get Redis to work

### ISSUE THREAD

**Issue by ericlaaper** [garethredfern/laravelvue-spa#8]
Hi, 

Thanks for a great starter. I used it to make a quick start for transferring my applications from LARAVEL/Vue integrated to Laravel hosted on Forge(Digital Ocean) and the frontend hosted on Firebase. Works perfectly. One problem, I can not get Redis to work. I can see in the app.php you commented out  'Redis' => Illuminate\Support\Facades\Redis::class,
I tried to activate it but as soon as I tried to get my application using redis for database queing I got errors. Do you have any idea?

**Comment by melvin78** [comment]
What sort of errors appeared?

**Comment by ericlaaper** [comment]
IN telescope: for example:
Call to undefined method App\Jobs\FSFULL\sendInvitation::payload()

**Comment by ericlaaper** [comment]
as soon I seed it to database or sync everything works perfect

**Comment by ericlaaper** [comment]
and in the log file : Call to undefined method App\Jobs\FSFULL\sendInvitation::payload() with context {
"userId": 1,
"exception": [
]
}

**Comment by ericlaaper** [comment]
Found it, it's actually a ray problem! After disabling ray everything works smoothly. Thanks a lot, Eric

**Comment by garethredfern** [comment]
Glad you found the starter files useful and sorted out your redis issue.
